import Head from "next/head";
import { Navbar } from "./components/navbar";
import { Utama } from "./components/utama";
import { Desc } from "./components/desc";
import { Cards } from "./components/cards";
import { Contact } from "./components/contact";
import { Footer } from "./components/footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Adopt Pet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Utama />
      <Desc />
      <Cards />
      <Contact />
      <Footer />
    </>
  );
}
